spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://gdsc-side.ct3lonfczwmg.ap-northeast-2.rds.amazonaws.com:3306/gdsc-side
    username: root
    password: 20181549
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: ture
        dialect:
  servlet:
     multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org.hibernate.sql: debug

cloud:
  aws:
    credentials:
      access-key: 
      secret-key: 
    s3:
      bucket: sch-gdsc-side
      base-url: https://sch-gdsc-side.s3.ap-northeast-2.amazonaws.com
    region:
      static: ap-northeast-2
    stack:
      auto: false
